[build-system]
requires = ["setuptools>=75.3","wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "pipetrt"
version = "0.1.2"
description = "TensorRT accelerated hand tracking library"
readme = "README.md"
requires-python = ">=3.8,<3.12"
license = { file = "LICENSE" }

authors = [
    { name = "Norifumi Kondo", email = "norifumi.kondo.it@gmail.com" }
]

keywords = [
    "TensorRT",
    "CUDA",
    "hand-tracking",
    "hand-landmark",
    "computer-vision",
]

dependencies = [
    "numpy",
    "opencv-python",
    "tensorrt",
    "cuda-python",
    "onnx",
    "nvidia-modelopt[onnx]",
    "pywin32; platform_system == 'Windows'",
]


[project.urls]
Homepage = "https://github.com/Konoa-1025/PipeTRT"
Repository = "https://github.com/Konoa-1025/PipeTRT"
Issues = "https://github.com/Konoa-1025/PipeTRT/issues"


[tool.setuptools.packages.find]
where = ["."]
include = ["pipetrt*"]
exclude = ["engines*"]
namespaces = false


[tool.setuptools.package-data]
pipetrt = [
    "models/*.onnx"
]